<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Ferremundo.Security.Contracts</PackageId>
    <Version>1.0.0-alpha.1</Version>
    <Authors>Ferremundo</Authors>
    <Company>Ferremundo</Company>
    <Description>Shared contracts for Ferremundo.Security.</Description>
    <RepositoryUrl>https://github.com/danielSempertegui/Ferremundo.Security.Sdk</RepositoryUrl>
    <PackageProjectUrl>https://github.com/danielSempertegui/Ferremundo.Security.Sdk</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
