<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Ferremundo.Security.Contracts\Ferremundo.Security.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Ferremundo.Security.Authentication</PackageId>
    <Version>1.0.0-alpha.1</Version>
    <Authors>Ferremundo</Authors>
    <Company>Ferremundo</Company>
    <Description>Ferremundo.Security authentication and permission authorization helpers for ASP.NET Core APIs.</Description>
    <RepositoryUrl>https://github.com/danielSempertegui/Ferremundo.Security.Sdk</RepositoryUrl>
    <PackageProjectUrl>https://github.com/danielSempertegui/Ferremundo.Security.Sdk</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" Version="7.5.0" />
    <PackageReference Include="OpenIddict.Validation.SystemNetHttp" Version="7.5.0" />
  </ItemGroup>
</Project>
